title = "Handmade in Berlin"
baseURL = "https://example.com"
languageCode = "de-de"
theme = "pedalpower"

MetaDataFormat = "yaml"
DefaultContentLanguage = "de"
SectionPagesMenu = "main"
Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "Handmade in Berlin"
  facebook = "https://www.facebook.com/Pedalpower-Tandems-und-Lastenfahrräder-handmade-in-Berlin-193112290700948/"
  instagram = "https://www.instagram.com/pedalpower_de/"
  youtube = "https://www.youtube.com/channel/UCV9hYQ5EAiNm7KTacjbmtBg/"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/header/header_tandem_01.jpg"
  recent_posts_number = 2
